#define TKSTRING                          1
#define TKEQUALS                          2
#define TKPATTERN                         3
#define TKDICT_START                      4
#define TKDICT_END                        5
#define TKSEND                            6
#define TKURL                             7
#define TKEXPECT                          8
#define TKNUMBER                          9
#define TKNEWLINE                        10
