#define TKEOF                             1
#define TKQSTRING                         2
#define TKPATTERN                         3
#define TKNUMBER                          4
#define TKIDENT                           5
#define TKEQ                              6
#define TKCLASS                           7
#define TKLPAREN                          8
#define TKRPAREN                          9
#define TKCOMMA                          10
#define TKLBRACE                         11
#define TKRBRACE                         12
#define TKLBRACKET                       13
#define TKRBRACKET                       14
#define TKCOLON                          15
