#!/usr/bin/env python

from subprocess import *
import sys
import os
import re
import time
import hashlib
import socket
from base64 import b64decode
import json
import getpass
import os
from threading import Thread, Condition

print "Connecting..."
CONN = socket.create_connection(('localhost', 6767), 3)

def read_msg():
    reply = ""

    ch = CONN.recv(1)
    while ch != '\0':
        reply += ch
        ch = CONN.recv(1)

    return json.loads(b64decode(reply))

def join_feed(user):
    CONN.send('@chat {"type": "join", "user": "%s"}\x00' % user)
    time.sleep(1)

def post_msg(user, data):
    msg = '@chat {"type": "msg", "user": "%s", "msg": "%s"}\x00' % (user, data)
    print "Sending events:", msg

    CONN.send(msg)

    print "SENT!"

user = getpass.getuser()

join_feed(user)
post_msg(user, "HI!")
print read_msg()

